# Generated by Django 2.2 on 2020-04-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_id',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('1', 'Student'), ('2', 'Alumni')], default='choice', max_length=300),
        ),
    ]
