# Generated by Django 2.2 on 2020-04-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_auto_20200428_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='mentor',
            field=models.ManyToManyField(to='alumni.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('student', 'Student'), ('alumni', 'Alumni')], default='choice', max_length=300),
        ),
    ]
