# Generated by Django 2.2 on 2020-04-28 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_auto_20200428_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='mentor',
        ),
        migrations.AddField(
            model_name='projects',
            name='mentor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='alumni.Profile'),
        ),
    ]
