# Generated by Django 2.2 on 2020-04-28 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_auto_20200428_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='mentor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumni.Profile'),
        ),
    ]
