# Generated by Django 2.2 on 2020-04-30 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0007_auto_20200428_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='alumni.Profile'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='mentor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='alumni.Profile'),
        ),
    ]
