# Generated by Django 2.2 on 2020-05-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0008_auto_20200430_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='author_name',
            field=models.CharField(default='Enter your username', max_length=500),
        ),
        migrations.RemoveField(
            model_name='projects',
            name='author',
        ),
        migrations.AddField(
            model_name='projects',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, related_name='author', to='alumni.Profile'),
        ),
    ]
