# Generated by Django 2.2 on 2020-05-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0009_auto_20200502_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='author_name',
        ),
    ]
