# Generated by Django 2.2 on 2020-05-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0010_remove_projects_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='author',
        ),
        migrations.AddField(
            model_name='projects',
            name='student1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='student2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='student3',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
