# Generated by Django 2.2 on 2020-05-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0011_auto_20200502_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='mentor',
        ),
        migrations.AddField(
            model_name='projects',
            name='mentor',
            field=models.ManyToManyField(blank=True, null=True, related_name='mentor', to='alumni.Profile'),
        ),
    ]
