# Generated by Django 2.2 on 2020-05-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0012_auto_20200502_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
