# Generated by Django 2.2 on 2020-05-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0014_auto_20200505_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_or_organisation',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_year',
            field=models.CharField(choices=[('1st year', '1st year'), ('2nrd year', '2nd year'), ('3rd year', '3rd year'), ('4th year', '4th year'), ('Working', 'Working')], max_length=500, null=True),
        ),
    ]
